export const PLAY_BUTTON_CLICK = "PLAY_BUTTON_CLICK";
export const STOP_BUTTON_CLICK = "STOP_BUTTON_CLICK";
export const TICK = "TICK";
export const TEMPO_CHANGED = "TEMPO_CHANGED";
export const STEP_BUTTON_CLICK = "STEP_BUTTON_CLICK";
export const MUTE_BUTTON_CLICK = "MUTE_BUTTON_CLICK";
export const CHANNEL_BUTTON_CLICK = "CHANNEL_BUTTON_CLICK";